language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

script:
  - ./gradlew checkstyle test